export const INITIATIAL_CALL = "INITIAL_CALL";
export const INITIATIAL_CALL_EVENT = "INITIAL_CALLEVENT";

export const RECOMMENDATION_CALL = "RECOMMENDATION_CALL";
export const RECOMMENDATION_CALL_EVENT = "RECOMMENDATION_CALL_EVENT";

export const TODAYS_DEAL = "TODAYS_DEAL";
export const TODAYS_DEAL_EVENT = "TODAYS_DEAL_EVENT";
